//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inkton {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inkton.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string api {
            get {
                return ResourceManager.GetString("api", resourceCulture);
            }
        }
        
        internal static string app {
            get {
                return ResourceManager.GetString("app", resourceCulture);
            }
        }
        
        internal static string archive {
            get {
                return ResourceManager.GetString("archive", resourceCulture);
            }
        }
        
        internal static string auto_register {
            get {
                return ResourceManager.GetString("auto_register", resourceCulture);
            }
        }
        
        internal static string auto_renew {
            get {
                return ResourceManager.GetString("auto_renew", resourceCulture);
            }
        }
        
        internal static string backup {
            get {
                return ResourceManager.GetString("backup", resourceCulture);
            }
        }
        
        internal static string bandwidth_gb_month {
            get {
                return ResourceManager.GetString("bandwidth_gb_month", resourceCulture);
            }
        }
        
        internal static string batch {
            get {
                return ResourceManager.GetString("batch", resourceCulture);
            }
        }
        
        internal static string configuration {
            get {
                return ResourceManager.GetString("configuration", resourceCulture);
            }
        }
        
        internal static string configured {
            get {
                return ResourceManager.GetString("configured", resourceCulture);
            }
        }
        
        internal static string cpu {
            get {
                return ResourceManager.GetString("cpu", resourceCulture);
            }
        }
        
        internal static string development_kit {
            get {
                return ResourceManager.GetString("development_kit", resourceCulture);
            }
        }
        
        internal static string domain {
            get {
                return ResourceManager.GetString("domain", resourceCulture);
            }
        }
        
        internal static string DomainNormal {
            get {
                return ResourceManager.GetString("DomainNormal", resourceCulture);
            }
        }
        
        internal static string DomainPrimary {
            get {
                return ResourceManager.GetString("DomainPrimary", resourceCulture);
            }
        }
        
        internal static string drive_ssd_gb {
            get {
                return ResourceManager.GetString("drive_ssd_gb", resourceCulture);
            }
        }
        
        internal static string flexible {
            get {
                return ResourceManager.GetString("flexible", resourceCulture);
            }
        }
        
        internal static string managed {
            get {
                return ResourceManager.GetString("managed", resourceCulture);
            }
        }
        
        internal static string memory_mb {
            get {
                return ResourceManager.GetString("memory_mb", resourceCulture);
            }
        }
        
        internal static string metrics {
            get {
                return ResourceManager.GetString("metrics", resourceCulture);
            }
        }
        
        internal static string mobile_desktop_console {
            get {
                return ResourceManager.GetString("mobile_desktop_console", resourceCulture);
            }
        }
        
        internal static string monitor {
            get {
                return ResourceManager.GetString("monitor", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_HTTP_400 {
            get {
                return ResourceManager.GetString("NEST_RESULT_HTTP_400", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_HTTP_401 {
            get {
                return ResourceManager.GetString("NEST_RESULT_HTTP_401", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_HTTP_403 {
            get {
                return ResourceManager.GetString("NEST_RESULT_HTTP_403", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_HTTP_ERROR {
            get {
                return ResourceManager.GetString("NEST_RESULT_HTTP_ERROR", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_DOMAIN_ALIAS_MALFORMED {
            get {
                return ResourceManager.GetString("NEST_RESULT_DOMAIN_ALIAS_MALFORMED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_DOMAIN_DEFAULT {
            get {
                return ResourceManager.GetString("NEST_RESULT_DOMAIN_DEFAULT", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_ADD_PAYMENT_METHOD {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_ADD_PAYMENT_METHOD", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_ASSIGN_TREE {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_ASSIGN_TREE", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_DEPLOYED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_DEPLOYED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_EXISTS {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_EXISTS", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_HANDLER_NEEDED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_HANDLER_NEEDED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_NDEPLOYED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_NDEPLOYED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_NREADY {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_NREADY", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_NUPDATES {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_NUPDATES", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_SERVICE_ALWAYS_ON {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_ALWAYS_ON", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_SERVICE_ESSENTIAL {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_ESSENTIAL", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_SERVICE_FTIER_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_FTIER_EXIST", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_EXIST", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_NDEDICATED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_NDEDICATED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_NEEDED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_NEEDED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_SERVICE_TIER_NSHARED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_SERVICE_TIER_NSHARED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_TAG_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_TAG_EXIST", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_CONTACT_EXCEEDED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_CONTACT_EXCEEDED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_CONTACT_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_CONTACT_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_DEPLOYMENT_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DEPLOYMENT_EXIST", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_DEPLOYMENT_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DEPLOYMENT_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_DEPLOYMENT_WRONGID {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DEPLOYMENT_WRONGID", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_DOMAIN_CERT_ASSIGNED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_CERT_ASSIGNED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_DOMAIN_CERT_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_CERT_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_DOMAIN_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_DOMAIN_UNREGISTERED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_UNREGISTERED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_FATAL {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FATAL", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_FIELDS {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FIELDS", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_FOREST_APP_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FOREST_APP_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_FOREST_INVALID {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FOREST_INVALID", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_FOREST_NOT_FOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FOREST_NOT_FOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_FOREST_NOT_PLANTABLE {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_FOREST_NOT_PLANTABLE", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_INVALID_SERVICE_LEVEL {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_INVALID_SERVICE_LEVEL", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_INVITATION_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_INVITATION_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_LOGIN_FAILED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_LOGIN_FAILED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_NAUTH {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_NAUTH", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_NEST_HANDLER_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_NEST_HANDLER_EXIST", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_NEST_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_NEST_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_NPLATFORM_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_NPLATFORM_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_PAYMENT_BUSY {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PAYMENT_BUSY", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_PAYMENT_DECLINED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PAYMENT_DECLINED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_PERM_FOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PERM_FOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_PERM_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PERM_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_PMETHOD_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PMETHOD_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_SERVICE_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SERVICE_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_SERVICE_TYPE_EXISTS {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SERVICE_TYPE_EXISTS", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_SUBSCRIPTION_INVALID {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SUBSCRIPTION_INVALID", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_SUBSCRIPTION_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SUBSCRIPTION_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_SUBSCRIPTION_STATE {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_SUBSCRIPTION_STATE", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_TREE_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TREE_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_USER_NAUTH {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_USER_NAUTH", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_USER_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_USER_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_NEST_HANDLER_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_NEST_HANDLER_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_SUCCESS {
            get {
                return ResourceManager.GetString("NEST_RESULT_SUCCESS", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_WARNING {
            get {
                return ResourceManager.GetString("NEST_RESULT_WARNING", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_WARNING_UPDATING {
            get {
                return ResourceManager.GetString("NEST_RESULT_WARNING_UPDATING", resourceCulture);
            }
        }
        
        internal static string scalable {
            get {
                return ResourceManager.GetString("scalable", resourceCulture);
            }
        }
        
        internal static string storage {
            get {
                return ResourceManager.GetString("storage", resourceCulture);
            }
        }
        
        internal static string team_management {
            get {
                return ResourceManager.GetString("team_management", resourceCulture);
            }
        }
        
        internal static string tier_1 {
            get {
                return ResourceManager.GetString("tier_1", resourceCulture);
            }
        }
        
        internal static string tier_2 {
            get {
                return ResourceManager.GetString("tier_2", resourceCulture);
            }
        }
        
        internal static string tier_3 {
            get {
                return ResourceManager.GetString("tier_3", resourceCulture);
            }
        }
        
        internal static string tier_4 {
            get {
                return ResourceManager.GetString("tier_4", resourceCulture);
            }
        }
        
        internal static string tier_5 {
            get {
                return ResourceManager.GetString("tier_5", resourceCulture);
            }
        }
        
        internal static string tier_6 {
            get {
                return ResourceManager.GetString("tier_6", resourceCulture);
            }
        }
        
        internal static string tier_7 {
            get {
                return ResourceManager.GetString("tier_7", resourceCulture);
            }
        }
        
        internal static string tier_8 {
            get {
                return ResourceManager.GetString("tier_8", resourceCulture);
            }
        }
        
        internal static string track {
            get {
                return ResourceManager.GetString("track", resourceCulture);
            }
        }
        
        internal static string users {
            get {
                return ResourceManager.GetString("users", resourceCulture);
            }
        }
        
        internal static string dedicated {
            get {
                return ResourceManager.GetString("dedicated", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_DOMAIN_IP {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_DOMAIN_IP", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_PAYMENT_OUTSTANDING {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PAYMENT_OUTSTANDING", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_BACKUP_IN_PROGRESS {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_BACKUP_IN_PROGRESS", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_PWD {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_PWD", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_APP_FINALIZE {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_APP_FINALIZE", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_SUCCESS_USER_PDELETE {
            get {
                return ResourceManager.GetString("NEST_RESULT_SUCCESS_USER_PDELETE", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_USER_EXIST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_USER_EXIST", resourceCulture);
            }
        }
        
        internal static string credit_deduction {
            get {
                return ResourceManager.GetString("credit_deduction", resourceCulture);
            }
        }
        
        internal static string invoice {
            get {
                return ResourceManager.GetString("invoice", resourceCulture);
            }
        }
        
        internal static string fail {
            get {
                return ResourceManager.GetString("fail", resourceCulture);
            }
        }
        
        internal static string login {
            get {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }
        
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_LIMIT_TO_24HOURS {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_LIMIT_TO_24HOURS", resourceCulture);
            }
        }
        
        internal static string tier_0 {
            get {
                return ResourceManager.GetString("tier_0", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_TAG_RESERVED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TAG_RESERVED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_IN_MAINTAINENCE {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_IN_MAINTAINENCE", resourceCulture);
            }
        }
        
        internal static string credit_award {
            get {
                return ResourceManager.GetString("credit_award", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_CREDIT_EXPIRED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_CREDIT_EXPIRED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_CREDIT_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_CREDIT_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_CREDIT_USED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_CREDIT_USED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_AEVENT_NFOUND {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_AEVENT_NFOUND", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_TRIAL_APP {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TRIAL_APP", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_CREDIT_WTIER {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_CREDIT_WTIER", resourceCulture);
            }
        }
        
        internal static string build {
            get {
                return ResourceManager.GetString("build", resourceCulture);
            }
        }
        
        internal static string jenkins_1 {
            get {
                return ResourceManager.GetString("jenkins_1", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_TRANSPORT {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TRANSPORT", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_TRANSPORT_BAD_REQUEST {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TRANSPORT_BAD_REQUEST", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_TRANSPORT_UNAUTHORIZED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TRANSPORT_UNAUTHORIZED", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_TRANSPORT_FORBIDDEN {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TRANSPORT_FORBIDDEN", resourceCulture);
            }
        }
        
        internal static string NEST_RESULT_ERROR_TRANSPORT_TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("NEST_RESULT_ERROR_TRANSPORT_TOKEN_EXPIRED", resourceCulture);
            }
        }
    }
}
